analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3459308,"name"\:"Sample - HR Web App \#3459308","teamId"\:3440205,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3485645,"accountId"\:null,"autoIntegrate"\:false,"sampleProject"\:false}
analytics.team={"id"\:3440205,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
